// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqW7DL7DTdMZqM35jshyk7oPBhseAjtiU',
    appId: '1:1001785425005:web:2b86f791c95f82c0b79364',
    messagingSenderId: '1001785425005',
    projectId: 'carlocation-5f161',
    authDomain: 'carlocation-5f161.firebaseapp.com',
    storageBucket: 'carlocation-5f161.firebasestorage.app',
    measurementId: 'G-T4HESZVC38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzi9aRpISn0SQxfmREx2wnftH1fPc_q4',
    appId: '1:1001785425005:android:6ff975feb7526496b79364',
    messagingSenderId: '1001785425005',
    projectId: 'carlocation-5f161',
    storageBucket: 'carlocation-5f161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHdJDt4q0jy5AGeCnQXm6ABTKWdv5_Ik',
    appId: '1:1001785425005:ios:a64d7b1e5f7efd14b79364',
    messagingSenderId: '1001785425005',
    projectId: 'carlocation-5f161',
    storageBucket: 'carlocation-5f161.firebasestorage.app',
    iosBundleId: 'com.example.carrentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHdJDt4q0jy5AGeCnQXm6ABTKWdv5_Ik',
    appId: '1:1001785425005:ios:a64d7b1e5f7efd14b79364',
    messagingSenderId: '1001785425005',
    projectId: 'carlocation-5f161',
    storageBucket: 'carlocation-5f161.firebasestorage.app',
    iosBundleId: 'com.example.carrentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqW7DL7DTdMZqM35jshyk7oPBhseAjtiU',
    appId: '1:1001785425005:web:1cc2c5ddaa23d2bdb79364',
    messagingSenderId: '1001785425005',
    projectId: 'carlocation-5f161',
    authDomain: 'carlocation-5f161.firebaseapp.com',
    storageBucket: 'carlocation-5f161.firebasestorage.app',
    measurementId: 'G-RCHBB1XLX2',
  );
}
